name: Frontend workflow

on:
  push:
    branches:
      - dev/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Frontend
      uses: actions/checkout@v2
    - name: Use Node.js 17.x
      uses: actions/setup-node@v1
      with:
        node-version: 17.x
    - name: Install Dependencies
      working-directory: ./client
      run: |
        npm install
        npm run build
    - name: Push Changes
      run: |
        git config --global user.name 'actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .
        git commit -am "Automated build of frontend"
        git push

    